import 'package:drive_app/src/feature/tickets/model/ticket_model.dart';
import 'package:get/get.dart';

class TicketController extends GetxController {
  List<TicketModel> tickets = <TicketModel>[
    TicketModel(
      title: 'Amman Bus',
      time: '21:00pm',
      img: "assets/image/logo (2).png",
      duration: '1:30 h',
      fromTime: '12:00',
      toTime: '14:00',
      fromTitle: 'Amman',
      toTitle: 'Zarqa',
      type: 'One way',
      price: '15 JOD',
    ),
    TicketModel(
      title: 'Irbid Express',
      time: '18:00pm',
      img: "assets/image/logo (2).png",
      duration: '2:00 h',
      fromTime: '16:00',
      toTime: '18:00',
      fromTitle: 'Irbid',
      toTitle: 'Amman',
      type: 'Round trip',
      price: '20 JOD',
    ),
    TicketModel(
      title: 'Aqaba Shuttle',
      time: '09:00am',
      img: "assets/image/logo (2).png",
      duration: '4:00 h',
      fromTime: '09:00',
      toTime: '13:00',
      fromTitle: 'Amman',
      toTitle: 'Aqaba',
      type: 'One way',
      price: '30 JOD',
    ),
    TicketModel(
      title: 'Madaba Tour',
      time: '10:30am',
      img: "assets/image/logo (2).png",
      duration: '1:00 h',
      fromTime: '10:30',
      toTime: '11:30',
      fromTitle: 'Amman',
      toTitle: 'Madaba',
      type: 'One way',
      price: '10 JOD',
    ),
    TicketModel(
      title: 'Jerash Bus',
      time: '14:00pm',
      img: "assets/image/logo (2).png",
      duration: '1:45 h',
      fromTime: '14:00',
      toTime: '15:45',
      fromTitle: 'Amman',
      toTitle: 'Jerash',
      type: 'One way',
      price: '12 JOD',
    ),
    TicketModel(
      title: 'Petra Express',
      time: '06:00am',
      img: "assets/image/logo (2).png",
      duration: '3:30 h',
      fromTime: '06:00',
      toTime: '09:30',
      fromTitle: 'Amman',
      toTitle: 'Petra',
      type: 'One way',
      price: '40 JOD',
    ),
  ];
}
