// ignore: depend_on_referenced_packages
import 'package:get/get.dart';

class LocalStrings extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'Reviews': 'Reviews',
          "EmailValidate": 'Please enter a valid email address',
          "PasswordValidation": 'Password must be at least 6',
          "PasswordOldValidation": 'Old Password must be at least 6',
          "PasswordNewValidation": "New Password must be at least 6",
          "logout": 'Logout',
          "email": 'Email:',
          "phone": 'Phone Number',
          "setting": 'Setting',
          "history": "History",
          "loginEmail": "Email",
          "loginPassword": "Password",
          "start": "Start",
          "dontHaveAccoint": "Don't Have Account ? ",
          "Register": "Register",
          "Login": "Login",
          "HaveAccount": "Have Account ? ",
          "confirmPassword": "Confirm Password",
          "loginName": "Name",
          "loginSecName": "Last Name",
          "nameValidation": "Name must be greater than 5 characters",
          "secNameValidation": "Last Name must be greater than 5 characters",
          "phoneValidation": "Phone number must be greater than 9",
          "VaildConfirmPassword": "Passwords do not match",
          "loginError": "Error in Phone number or Password",
          "loginSuccess": "Login Successfully",
          "library": "Choose from library",
          "camera": "Take photo",
          "slecetGender": "Please Select Gender",
          "slecetCountry": "Please Select Country",
          "Select a Gender": "Select a Gender",
          'Gender': "Gender",
          'noEnternet': "No internet connection",
          'changePassword': "Change Password",
          'Forget Password': "Forget Password",
          'No worries! Enter your old password below':
              'No worries! Enter your old password below',
          'oldPassword': 'Old Password',
          'newPassowrd': 'New Password',
          "Rides": "Rides",
          "RidesCount": "Rides",
          "Statistics": "Statistics",
          "Add Rides": "Add Rides",
          "waiting": "Waiting",
          "addRide": "Add Ride",
          "Start Time": "Start Time",
          "End Time": "End Time",
          "Start Date": "Start Date",
          "End Date": "End Date",
          'Male': 'Male',
          'Female': 'Female',
          "Select Gender": "Select Gender",
          "Select Driver": "Select Driver",
          "Driver": "Driver",
          'From Location': 'Start Location',
          'To Location': 'End Location',
          "Profile": "Profile",
          "Name": "Name",
          "Email": "Email",
          "Sign In": "Sign In",
          'Student Id': 'Student Id',
          'Admin': 'Admin',
          "Or": "Or",
          "Don’t have an account?": "Don’t have an account?",
          "Sign up": "Sign up",
          "All Rides": "All Rides",
          "accept": "accept",
          "Accpted": "Accepted",
          "Rejected": "Rejected",
          "reject": "reject",
          "In Progress": "In Progress",
          "Started": "Started",
          "see all": "see all",
          "Today's trips": "Today's trips",
          //
          "To": "To",
          "From": "From",
          "Hey": "Hey",
          "Ticket No.": "Ticket No.",
          "Boarding Point": "Boarding Point",
          "Drop Point": "Drop Point",
          "Completed": "Completed",
          "Total": "Total",
          "Done": "Done",
          "Today": "Today",
          "Tomorrow": "Tomorrow",
          "Other": "Other",
          "Find Buses": "Find Buse",
          "matchSearch": "Matching Rides",
          "otherRides": 'Other Available Rides',
          "cancel": "cancel",
          "Tickets": "Tickets",
          "Book": "Book",
          "Next": "Next",
          "Booked": "Booked",
          "Available": "Available",
          "Your Seat": "Your Seat",
          "Write a review message:": "Write a review message:",
          'Selected Seat': 'Selected Seat',
          'No seat selected': 'No seat selected',
          "You don’t have a ticket.": "You don’t have a ticket.",

          ///
          'No Rides for today': 'No Rides for today',
          'No Rides for you': 'No Rides for you',
          'No Comment For this ride': 'No Comment For this ride',

          ///
          'Sign In as Admin': 'Sign In as Admin',
          'Sign In as Driver': 'Sign In as Driver',
          "Message": "Message",
          "later": "later",
          "Submit": "Submit",
          "Rate": "Rate",
          "Rating": "Rating",
          "All Rating": "All Rating",
          "Most Booked Rides": "Most Booked Rides",
          "Booking Count": "Booking Count",
        },
        'ar_JO': {
          'No Comment For this ride': "لا تعليق على هذه الرحلة",
          "Booking Count": "عدد مرات الحجز",
          "All Rating": " جميع التقييمات",
          "Most Booked Rides": "الرحلات الأكثر حجزًا",
          "Submit": "إرسال",
          "Rate": "تقييم",
          "Rating": "التقيممات",
          "later": "لاحقا",
          "Message": "رسالة...",
          'No Rides for you': 'لا توجد رحلات',
          "Write a review message:": "اكتب رسالة مراجعة:",
          'No Rides for today': 'لا توجد رحلات اليوم',
          'Sign In as Admin': 'تسجيل الدخول كمسؤول',
          'Sign In as Driver': 'تسجيل الدخول كسائق',
          "You don’t have a ticket.": "لم يتم العثور على تذكرة لك.",
          "Tickets": "التذاكر",
          "Book": "احجز",
          "Next": "التالي",
          "Booked": "محجوز",
          "Available": "متاح",
          "Your Seat": "مقعدك",
          "Selected Seat": "المقعد المحدد",
          "No seat selected": "لم يتم تحديد مقعد",
          "No rides found.": "لم يتم العثور على رحلات",
          "matchSearch": "الرحلات المطابقة لبحثك",
          "otherRides": "رحلات أخرى متاحة",
          "cancel": "الغاء",
          "Find Buses": 'البحث عن الحافلة',
          "Today": "اليوم",
          "Tomorrow": "غـدا",
          "Other": "غير ذلك",
          "Done": "الرحلات المنجزة",
          "Total": "المجموع",
          "Completed": "انتهت الرحلة",
          'Gender': "جنس",
          'male': "ذكر",
          'female': "انثى",
          "Drop Point": "نقطة التوصيل ",
          "Boarding Point": "نقطة الانطلاق",
          "Ticket No.": "رقم البطاقة",
          "Sign up": "إنشاء حساب",
          "All Rides": "جميع الرحلات",
          "accept": "قبول",
          "Accpted": "تم القبول",
          "Rejected": "مرفوض",
          "reject": "رفض",
          "In Progress": "قيد التنفيذ",
          "Started": "بدأت",
          "see all": "عرض الكل",
          "Today's trips": "رحلات اليوم",
          "Reviews": "المراجعات",
          "EmailValidate": "يرجى إدخال بريد إلكتروني صالح",
          "PasswordValidation": "يجب أن تكون كلمة المرور 6 أحرف على الأقل",
          "PasswordOldValidation":
              "يجب أن تكون كلمة المرور القديمة 6 أحرف على الأقل",
          "PasswordNewValidation":
              "يجب أن تكون كلمة المرور الجديدة 6 أحرف على الأقل",
          "logout": "تسجيل الخروج",
          "email": "البريد الإلكتروني:",
          "phone": "رقم الهاتف",
          "setting": "الإعدادات",
          "history": "السجل",
          "loginEmail": "البريد الإلكتروني",
          "loginPassword": "كلمة المرور",
          "dontHaveAccoint": "ليس لديك حساب؟",
          "Register": "إنشاء حساب",
          "Login": "تسجيل الدخول",
          "HaveAccount": "لديك حساب؟",
          "confirmPassword": "تأكيد كلمة المرور",
          "loginName": "الاسم",
          "loginSecName": "الاسم الأخير",
          "nameValidation": "يجب أن يكون الاسم أطول من 5 أحرف",
          "secNameValidation": "يجب أن يكون الاسم الأخير أطول من 5 أحرف",
          "phoneValidation": "يجب أن يكون رقم الهاتف أطول من 9 أرقام",
          "VaildConfirmPassword": "كلمتا المرور غير متطابقتين",
          "loginError": "خطأ في رقم الهاتف أو كلمة المرور",
          "loginSuccess": "تم تسجيل الدخول بنجاح",
          "library": "اختر من المعرض",
          "camera": "التقاط صورة",
          "slecetGender": "يرجى تحديد الجنس",
          "slecetCountry": "يرجى تحديد الدولة",
          "Select a Gender": "اختر الجنس",
          "noEnternet": "لا يوجد اتصال بالإنترنت",
          "changePassword": "تغيير كلمة المرور",
          "Forget Password": "هل نسيت كلمة المرور؟",
          "No worries! Enter your old password below":
              "لا تقلق! أدخل كلمة المرور القديمة أدناه",
          "oldPassword": "كلمة المرور القديمة",
          "newPassowrd": "كلمة المرور الجديدة",
          "addRide": "إضافة رحلة",
          "Profile": "الملف الشخصي",
          "Name": "الاسم",
          "Email": "البريد الإلكتروني",
          "Sign In": "تسجيل الدخول",
          "Student Id": "رقم الطالب",
          "Admin": "مسؤول",
          "Or": "أو",
          "Don’t have an account?": "ليس لديك حساب؟",
          "Rides": "الرحلات",
          "RidesCount": "رحل",
          "Statistics": "الإحصائيات",
          "Add Rides": "إضافة رحلات",
          "waiting": "في الانتظار",
          "Start Time": "وقت البدء",
          "End Time": "وقت الانتهاء",
          "Start Date": "تاريخ البدء",
          "End Date": "تاريخ الانتهاء",
          "Male": "ذكر",
          "Female": "أنثى",
          "Select Gender": "اختر الجنس",
          "Select Driver": "اختر السائق",
          "Driver": "السائق",
          "From Location": "موقع البداية",
          "To Location": "موقع النهاية",
          "To": "إلى",
          "From": "من",
          "Hey": "مرحبًا"
        }
      };
}
