// ignore: depend_on_referenced_packages
import 'package:get/get.dart';

class LocalStrings extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'Reviews': 'Reviews',
          "EmailValidate": 'Please enter a valid email address',
          "PasswordValidation": 'Password must be at least 6',
          "PasswordOldValidation": 'Old Password must be at least 6',
          "PasswordNewValidation": "New Password must be at least 6",
          "logout": 'Logout',
          "email": 'Email:',
          "phone": 'Phone Number',
          "setting": 'Setting',
          "history": "History",
          "loginEmail": "Email",
          "loginPassword": "Password",
          "start": "Start",
          "dontHaveAccoint": "Don't Have Account ? ",
          "Register": "Register",
          "Login": "Login",
          "HaveAccount": "Have Account ? ",
          "confirmPassword": "Confirm Password",
          "loginName": "Name",
          "loginSecName": "Last Name",
          "nameValidation": "Name must be greater than 5 characters",
          "secNameValidation": "Last Name must be greater than 5 characters",
          "phoneValidation": "Phone number must be greater than 9",
          "VaildConfirmPassword": "Passwords do not match",
          "loginError": "Error in Phone number or Password",
          "loginSuccess": "Login Successfully",
          "library": "Choose from library",
          "camera": "Take photo",
          "slecetGender": "Please Select Gender",
          "slecetCountry": "Please Select Country",
          "Select a Gender": "Select a Gender",
          'Gender': "Gender",
          'noEnternet': "No internet connection",
          'changePassword': "Change Password",
          'Forget Password': "Forget Password",
          'No worries! Enter your old password below':
              'No worries! Enter your old password below',
          'oldPassword': 'Old Password',
          'newPassowrd': 'New Password',
          "Rides": "Rides",
          "Statistics": "Statistics",
          "Add Rides": "Add Rides",
          "Hey": "Hey",
          "From": "From",
          "To": "To",
          "waiting": "Waiting",
          "accepted": "Accepted",
          "addRide": "Add Ride",
          "Start Time": "Start Time",
          "End Time": "End Time",
          "Start Date": "Start Date",
          "End Date": "End Date",
          'Male': 'Male',
          'Female': 'Female',
          "Select Gender": "Select Gender",
          "Select Driver": "Select Driver",
          "Driver": "Driver",
          'From Location': 'Start Location',
          'To Location': 'End Location',
          "Profile": "Profile",
          "Name": "Name",
          "Email": "Email",
          "Sign In": "Sign In",
          'Student Id': 'Student Id',
          'Admin': 'Admin',
          "Or": "Or",
          "Don’t have an account?": "Don’t have an account?",
          "Sign up": "Sign up",

        },
        'ar_JO': {
          "Reviews": "المراجعات",
          "EmailValidate": "يرجى إدخال بريد إلكتروني صالح",
          "PasswordValidation": "يجب أن تكون كلمة المرور 6 أحرف على الأقل",
          "PasswordOldValidation":
              "يجب أن تكون كلمة المرور القديمة 6 أحرف على الأقل",
          "PasswordNewValidation":
              "يجب أن تكون كلمة المرور الجديدة 6 أحرف على الأقل",
          "logout": "تسجيل الخروج",
          "email": "البريد الإلكتروني:",
          "phone": "رقم الهاتف",
          "setting": "الإعدادات",
          "history": "السجل",
          "loginEmail": "البريد الإلكتروني",
          "loginPassword": "كلمة المرور",
          "dontHaveAccoint": "ليس لديك حساب؟",
          "Register": "إنشاء حساب",
          "Login": "تسجيل الدخول",
          "HaveAccount": "لديك حساب؟",
          "confirmPassword": "تأكيد كلمة المرور",
          "loginName": "الاسم",
          "loginSecName": "الاسم الأخير",
          "nameValidation": "يجب أن يكون الاسم أطول من 5 أحرف",
          "secNameValidation": "يجب أن يكون الاسم الأخير أطول من 5 أحرف",
          "phoneValidation": "يجب أن يكون رقم الهاتف أطول من 9 أرقام",
          "VaildConfirmPassword": "كلمتا المرور غير متطابقتين",
          "loginError": "خطأ في رقم الهاتف أو كلمة المرور",
          "loginSuccess": "تم تسجيل الدخول بنجاح",
          "library": "اختر من المعرض",
          "camera": "التقاط صورة",
          "slecetGender": "يرجى تحديد الجنس",
          "slecetCountry": "يرجى تحديد الدولة",
          "Select a Gender": "اختر الجنس",
          "noEnternet": "لا يوجد اتصال بالإنترنت",
          "changePassword": "تغيير كلمة المرور",
          "Forget Password": "هل نسيت كلمة المرور؟",
          "No worries! Enter your old password below":
              "لا تقلق! أدخل كلمة المرور القديمة أدناه",
          "oldPassword": "كلمة المرور القديمة",
          "newPassowrd": "كلمة المرور الجديدة",
          "addRide": "إضافة رحلة",
          "Profile": "الملف الشخصي",
          "Name": "الاسم",
          "Email": "البريد الإلكتروني",
          "Sign In": "تسجيل الدخول",
          "Student Id": "رقم الطالب",
          "Admin": "مسؤول",
          "Or": "أو",
          "Don’t have an account?": "ليس لديك حساب؟"
        }
      };
}
